# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ba448bdd6a8c9a7f63b21f42fe32b6c5137784468ed2e84c8b6e4ab95c4abcfc10377d13e49f3f3e61f463a13dcdc9c0e914e6ff24de60613db47ac4d53d58e

test:
  secret_key_base: daff360c2bf23c8d67e6ef29bb806be5d6c69807a5278ca756529fd849e9d8413553257ecc0b78c7d20ddcb14485cfb3d57647fcd8824fa94329932d8b312ef0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
